### ISSUE TITLE
Library not working  on windows 

### ISSUE THREAD

**Issue by priyanshus1** [sainteos/tmxparser#39]
Hi unbale to compile it with MXE can you please upload a library for mingw32 working.
Need it urgently if possible  
Thanks

**Comment by dylanetaft** [comment]
I just downloaded a local copy and hacked it into my own app's cmake file.
#tmxlib stuff
configure_file(
  "${PROJECT_SOURCE_DIR}/engine/externlib/tmxparser/src/Tmx.h.in"
  "${PROJECT_SOURCE_DIR}/engine/externlib/tmxparser/src/Tmx.h"
)
file(GLOB_RECURSE TMXPARSERSOURCES ${PROJECT_SOURCE_DIR}/engine/externlib/tmxparser/src/*.cpp)
#end tmxlib stuff

Then in in your add_executable line you can add ${TMXPARSERSOURCES}
Probably a better way to do this for CMake warlocks, but this works well for me.

**Comment by sainteos** [comment]
Windows building is not officially supported, however I have been able to successfully do a windows build by including all of the source within the include directory for the project I was compiling with mingw.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
