### ISSUE TITLE
Build and test fails on GNU/Linux

### ISSUE THREAD

**Issue by richelbilderbeek** [sainteos/tmxparser#42]
Building the code of `tmxparser` goes fine. 

```
mkdir build
cd build
cmake ..
make
sudo make install
```

And thumbs up for having tests! Sure I run these:

```
./run_tests
```

Too bad, this results in:

```
error code: 2
error text: ./example/example.tmx
```

I already noticed that [SFML-tmxloader](https://github.com/fallahn/sfml-tmxloader) and [STP](https://github.com/edoren/STP) also fail, so I guess it is somewhere upstream. Those projects use `zlib` as well, yet use `pugixml` to parse XML. My uneducated guess would be that Tiled has changed its XML format, but I would not dare to bet on it.

Information about my system:

```
$ uname -a
Linux [...] 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:34:49 UTC 2016 i686 athlon i686 GNU/Linux
```

Note I actually use Lubuntu (with the L of Leonardo) Xenial with the recommended updates.

I volunteer to help, but would like a little push in the right direction. Perhaps also the problem is trivial for you guys.

Cheers, Richel Bilderbeek

**Comment by tamatias** [comment]
`run_tests` is meant to be run from the `test` folder.
Try `( TEST_FOLDER=../; TMXPARSER_BUILD=$PWD; cd $TEST_FOLDER && ${TMXPARSER_BUILD}/run_tests )` from your build folder.

**Comment by richelbilderbeek** [comment]
Indeed, `mxparser/test`, running `./../build/run_tests` succeeds! May I suggest to document this? I volunteer to do so using a Pull Request .

**Comment by sainteos** [comment]
Test running instructions are now indicated within the readme. 👍

**Comment by richelbilderbeek** [comment]
Smashing! Thanks!
