### ISSUE TITLE
Suggestion: add Travis CI support

### ISSUE THREAD

**Issue by richelbilderbeek** [sainteos/tmxparser#46]
I enjoy and use the continuous integration service Travis CI a lot.

I suggest to add it to `tmxparser`, to show the high quality of the code.

As you do have your tests in place (which convinces me of a certain level of professionalism), I volunteer to add it to this GitHub. 

Feel free to reject, do it yourself or let me do it :-)

**Comment by sainteos** [comment]
Travis-CI building complete and in master.

**Comment by richelbilderbeek** [comment]
You're awesome!
