### ISSUE TITLE
Get the right texture from tile

### ISSUE THREAD

**Issue by PucklaMotzer09** [sainteos/tmxparser#52]
I am currently implementing this parser into my engine. I have started with rendering the tiles. I have calculated the coordinates of the tile on the tileset using the id of the tile, but I am getting into problems if the tileset has spacing and margin or the tileset consists of different images.
What is the right way to get the pixelcoordinates of a tile?

**Comment by sainteos** [comment]
I know it's 11 months later, but a code example and screenshots would be really helpful to see to troubleshoot this. What is your method of calculating the location currently?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dylanetaft** [comment]
It's working fine for me - here is some sample code
See the section around 
int sx, sy, sw, sh, dx, dy;


void Map::genRenderCache() {
	int mwidth = GetWidth();
	int mheight = GetHeight();
	int twidth = GetTileWidth();
	int theight = GetTileHeight();
	int layerCounter = 0;
	for (auto &layer : GetTileLayers()) {
		RenderFrame rset;
		std::string texpath;
		for (int y = 0;y < mheight;y++) {
			for (int x=0;x < mwidth;x++) {
				const Tmx::MapTile &tile = layer->GetTile(x,y);
				Uint32 gid = tile.gid;
				if (gid == 0) continue; //no tile here
				int tid = tile.tilesetId;
				const Tmx::Tileset *tileset = GetTileset(tid);
				texpath = "img/tilesets/" + tileset->GetImage()->GetSource(); //path to the image
				int texid = Engine::getInstance()->getTextureId(texpath); //my own resource manager
				gid = gid - tileset->GetFirstGid(); //offset GID so we can get x\y
				int tscols = tileset->GetColumns();
				int tswidth = twidth * tscols; //tileset width would be tileset columns * tile width
				int sx, sy, sw, sh, dx,dy;
				sx = (gid - ((gid / tscols) * tscols)) * twidth; //x position of a tile in the tileset
				sy = (gid / tscols) * theight; //y position of a tile in the tileset

				sw = twidth;
				sh = theight;
				dx = x * twidth;
				dy = y * theight;
				rset.renderInstructions.push_back(RenderableBehavior::createPart(sx, sy, sw, sh, dx, dy,texid)); //I basically re-map the map data into a vector that has raw coordinates, so I can render it like every other game object I have
			}
		}
		setLayer(layerCounter); //mark this layer as available 
		layerCounter++;
		_cachedRenderFrameSet.push_back(rset);
	}
}
