### ISSUE TITLE
Custom Tile Properties

### ISSUE THREAD

**Issue by infrared511** [sainteos/tmxparser#71]
I have a tileset that I added custom properties to each individual tile. I don't understand how do retrieve the information in my code. 
I want to get the custom property from the individual tile.

tileset = new Tmx::Tileset();
tileset = map->GetTileset(0);
tileset->GetTile(ID)->GetProperties().GetFloatProperty("friction.x"); 

Now this doesn't work, but need to know the proper way to get this to work. For whatever reason, I can't get an individual propery for a tile. 
 
Thanks.

**Comment by sainteos** [comment]
I need a little bit more information to be able to help with this. What output are you getting in the console when you run it? Where do you get "ID" from? The method is FindTileset not GetTileset, are you verifying that the map is getting a tileset? There are many things that could be going wrong with the code you have provided, so I probably need a bit more context.

Another thing, you are leaking memory if you do `tileset = new Tmx::Tileset()` and then reassign the tileset pointer in the next line.
