### ISSUE TITLE
MapRenderOrder::TMX_LEFT_DOWN has the same value as MapRenderOrder::TMX_LEFT_UP

### ISSUE THREAD

**Issue by LiquidityC** [sainteos/tmxparser#78]
Not sure if this is a bug or not but it got me confused:

https://github.com/sainteos/tmxparser/blob/da62e19cdd3dd76ec72c85c7a2905e3ab491df0e/include/TmxMap.h#L87

**Comment by sainteos** [comment]
Looks to be a bug. I went to the tiled source to verify and sure enough, LEFT_DOWN and LEFT_UP should not be the same.
https://github.com/bjorn/tiled/blob/e146b0d6c653d00fbba4574e9cc858811d1ea959/src/tiled/editablemap.h#L88
